- name: configure fronted service
  become: yes
  hosts: frontend
  tasks:
  - name: install nginex server
    ansible.builtin.dnf:
      name: nginex
      state: latest
        
  - name: start and enable nginex
    ansible.builtin.service:
      name: nginex
      state: started
      enabled: yes

  - name: delete default website
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent